# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - robocol_arm_group_controller

  robocol_arm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robocol_joint1
      - robocol_joint2
      - robocol_joint3
      - robocol_joint4
      - robocol_joint5
      - robocol_joint6